[package]
name = "bot451"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bot"
path = "src/bot/bin/main.rs"

[[bin]]
name = "distributed_bot"
path = "src/distributed_bot/bin/main.rs"

[workspace]
members = [
    "crates/botbackend",
]

[workspace.dependencies]
tokio = { version = "1.29.1", features = ["full"] }
teloxide = { version = "0.12", features = ["macros"] }
anyhow = { version = "1.0" }
tempfile = "3"
async-trait = "0.1.78"
dptree = "0.3.0"

[dependencies]
tokio.workspace = true
teloxide.workspace = true
anyhow.workspace = true
dptree.workspace = true
botbackend = { path = "crates/botbackend" }
