[package]
name = "botbackend"
version = "0.1.0"
edition = "2021"

[lib]
name = "botbackend"
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
async-trait  = { workspace = true }
