[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
sqlx = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
time = { workspace = true }
