name: Publish Docker image to gitea

on:
  push:
    branches: [ "master" ]

jobs:
  push_to_registries:
    name: Push Docker image to Gitea Container Registry
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    permissions:
      packages: write

    strategy:
      matrix:
        variant: [ bot, backend ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            ${{ vars.REGISTRY_URL }}/${{ gitea.repository_owner }}/${{ matrix.variant }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          dockerfile: Dockerfile.${{ matrix.variant }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.WORKFLOW_TOKEN }}