[package]
name = "api"
version = "0.1.0"
edition = "2021"

[lib]
name = "api"
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
time = { workspace = true }